# Generated by Django 5.0.3 on 2024-04-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoukhin', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
