# Generated by Django 5.0.3 on 2024-04-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoukhin', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThEkdcrvvZTX2D_5QTsg6RZxiPVlo3rGzOPs--1ztLhQGBMIVlTXQgGYYYcQ&s', null=True, upload_to='static/images'),
        ),
    ]
