# Generated by Django 5.0.3 on 2024-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoukhin', '0013_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(blank=True, default='+880', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about_myself',
            field=models.TextField(blank=True, default='will add later', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='static/images/default_no_img.jfif', null=True, upload_to='static/images'),
        ),
    ]
