# Generated by Django 5.0.3 on 2024-05-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoukhin', '0014_customuser_contact_no_alter_customuser_about_myself_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nid', models.CharField(max_length=20)),
                ('contact_no', models.CharField(blank=True, default='+880', max_length=20, null=True)),
                ('account_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('picture', models.ImageField(blank=True, default='static/images/default_no_img.jfif', null=True, upload_to='static/images')),
                ('about_myself', models.TextField(blank=True, default='will add later', null=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
